#!/bin/bash

base="/home/phn/Documents/WoodWorking/Projects/Live-edge-table"
input="profile-bezier.svg"
colors="profile-bezier-colors.svg"
function convert_file() {

infile=$base/$1/$input
colorfile=$base/$1/$colors
arcfile=$base/$1/"gabarit-"$1".svg"

python -m bezier2arc --list -i $infile
python -m bezier2arc --color -i $infile -o $colorfile
python -m bezier2arc --convert -i $infile -o $arcfile
python -m bezier2arc --list -i $arcfile
}

convert_file table-5

